

const Footer = () => {
    return (
        <footer>
            <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Saepe odio voluptas provident officia perspiciatis sint ducimus itaque pariatur aliquid, nesciunt ullam id. Modi vero cumque, aperiam at voluptatum incidunt perferendis, culpa, maiores eaque molestiae deleniti rerum optio ad dolore? Quae sed rem qui, aut cupiditate praesentium id ipsam non ab ratione magni quo veritatis at ducimus voluptatem optio temporibus eius excepturi quasi dolor! Voluptates voluptatem voluptate sit nobis veritatis fugiat at? Voluptate, ea vitae? Hic nam non voluptatibus eos, aut saepe consectetur autem assumenda asperiores incidunt nemo vero. Necessitatibus, consectetur accusantium, corporis totam delectus ut unde architecto molestiae facilis nulla modi repellendus, aliquam similique et laborum quia suscipit distinctio iure? Eligendi, libero? Nostrum dicta dolores, recusandae dolore ab labore tenetur vitae odio facere dolorem quibusdam. Voluptatem esse cum suscipit nisi quibusdam. Quibusdam saepe enim obcaecati velit pariatur cupiditate labore, assumenda officiis itaque, inventore aperiam magni dignissimos ad at exercitationem debitis quaerat modi! Sunt saepe magnam, commodi perferendis esse est consequuntur error ipsum praesentium officia amet harum voluptas. Minus, debitis ab doloremque illum, aspernatur illo iusto, quae iure tenetur neque eos! Incidunt ut, consequatur molestiae quibusdam qui rem ex praesentium fuga dolores dolorum quae accusantium repudiandae earum laborum doloribus? Quam quas temporibus laboriosam id in, officia asperiores culpa sit impedit praesentium, quisquam architecto officiis tempora velit repellat iste doloremque atque tenetur dolor quaerat totam voluptas maiores vel! Blanditiis nulla, voluptatibus consequuntur odio similique harum doloribus incidunt fuga sapiente itaque, fugit impedit sed earum quam reiciendis beatae aspernatur corrupti ad id facilis. Accusamus facilis enim neque tempora! Aliquid accusantium, corporis officia repellendus vero ullam mollitia explicabo iusto tempora dignissimos debitis, itaque aliquam eaque quod ipsam. Cumque cupiditate impedit illo quae ab, rerum nisi consectetur accusantium dolores, quas similique libero. Amet culpa, sint id, libero mollitia beatae quae eum error magni repellendus ex!dvvcsvsvsdvsdvsdvssdvsdvsdvsdvsdvsvvvvvvvvvvvvvvvvvvvv</h1>
        </footer>
    );
};

export default Footer;