export const metadata = {
    title: "Blog",
    description: "Generated by Next.js",
  };

export default function RootLayout({
    children,
  }: {
    children: React.ReactNode;
  }) {
    return (
        <section className="blog">
            {children}
        </section>
    )
  }
  